### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by kiruhasas22** [Burgerballs/psychcharactertocodename#1]
i get this 
SUCCESSFULLY LOADED JSON
Traceback (most recent call last):
  File "C:\Users\ПК\Downloads\script\psychjsontocodenamexml.py", line 80, in <module>
    newfile = convert(textfile)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Downloads\script\psychjsontocodenamexml.py", line 47, in convert
    specialChoice = sC()
                    ^^^^
  File "C:\Users\ПК\Downloads\script\psychjsontocodenamexml.py", line 32, in sC
    textfileee = open('config.json', "r").read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by kiruhasas22** [comment]
and python: can't open file 'C:\\Users\\ПК\\psychjsontocodenamexml.py': [Errno 2] No such file or directory

**Comment by Burgerballs** [comment]
You need to put the config.json from the zip into the same directory as the script or it will not function
